### ISSUE TITLE
FontManager.cpp build error

### ISSUE THREAD

**Issue by ghost** [OpenTechEngine/Discussions#13]
ran make and got terminated with FontManager.cpp, I think it is the 'all' build target.

```
compilation terminated.
libs/cegui/CEGUI.git/cegui/src/CMakeFiles/CEGUIBase-0.dir/build.make:1066: recipe for target 'libs/cegui/CEGUI.git/cegui/src/CMakeFiles/CEGUIBase-0.dir/FontManager.cpp.o' failed
make[2]: *** [libs/cegui/CEGUI.git/cegui/src/CMakeFiles/CEGUIBase-0.dir/FontManager.cpp.o] Error 1
CMakeFiles/Makefile2:363: recipe for target 'libs/cegui/CEGUI.git/cegui/src/CMakeFiles/CEGUIBase-0.dir/all' failed
make[1]: *** [libs/cegui/CEGUI.git/cegui/src/CMakeFiles/CEGUIBase-0.dir/all] Error 2
Makefile:137: recipe for target 'all' failed
make: *** [all] Error 2
```

Running make with the ignore error flag, it's compiling the code, with some warnings and errors.

**Comment by kortemik** [comment]
You need freetype-devel installed. It's a misconfiguration in our CMake
that it doesn't detect if you don't have it and build from source. It's
built only on windows.

**Comment by ghost** [comment]
I've got the freetype6-dev packages installed and tried freetype\* as well. Doesn't seem to work, so i'll build on Win. Any way to work around this to get a Linux binary of the engine?

**Comment by kortemik** [comment]
Let me fix the cmake... :|

**Comment by kortemik** [comment]
https://github.com/OpenTechEngine/OpenTechBFG/commit/49b9af6640f4099e013a6d48a7a876b42a79871f

as promised

**Comment by ghost** [comment]
@kortemik Thank you, you're a legend.
