### ISSUE TITLE
KTX file format request

### ISSUE THREAD

**Issue by ghost** [OpenTechEngine/Discussions#21]
I'm working on textures for the game and would like to use a compressed format which has no legal restrictions. So I looked up alternatives and found out about the Kronos group KTX format. This is similar to the DDS format without the S3TC patent issues. Would you guys consider adding in the libktx into the engine? Here is the Kronos link to the format.

https://www.khronos.org/opengles/sdk/tools/KTX/

**Comment by kortemik** [comment]
Yes I can take a look at it, wouldn't hurt to use such version as most FOSS
distributions don't come with s3tc decoders.

**Comment by DanielGibson** [comment]
doesn't look _that_ interesting.. seems to be a container to store textures, and "Textures can be stored in any of the compressed formats supported by OpenGL family APIs and extensions or can be stored uncompressed".
The thing is that afaik s3tc is the only widely supported compression - ETC and ASTC are only supported by mobile, not by desktop GPUs (at least with commonly used drivers), afaik.
So I guess FOSS driver users will have to compile their own drivers with s3tc support or use the patent free S2TC alternative (which supplies the S3TC OpenGL extensions without actually implementing S3TC and looks a bit worse).

**Comment by DanielGibson** [comment]
Ok, there seem to be two compressed formats with some support on desktop hardware that are supported by mesa: RGTC (https://www.opengl.org/registry/specs/EXT/texture_compression_rgtc.txt) and BPTC (https://www.opengl.org/wiki/BPTC_Texture_Compression)

This is just for the record and doesn't mean we should try to make OTE use it, as the s3tc/DXT based stuff works well and is well integrated in the engine with very optimized code to generate the compressed textures from uncompressed ones etc.
(For Rage they used the same format for megatextures and they released the code to compress that on the fly as needed)

**Comment by ghost** [comment]
I agree it seems it would be a waste of time, I read KTX is not widely used and plugin support for software seems to be lacking for most software.
