### ISSUE TITLE
Back facing occlusion and LOD

### ISSUE THREAD

**Issue by ghost** [OpenTechEngine/Discussions#22]
Would it be possible to do some kind of per model back facing occlusion and LOD models in the engine  to help optimize scenes using high poly models? Some modern games have characters with models going up to 200K+, I'd like to do character/weapon models and some static models with higher poly counts but feel it may cause issues. Currently I'm modelling with lower polys/triangles and splitting up higher poly static models based on what BFG uses.

**Comment by BielBdeLuna** [comment]
ATM the unique LOD system implemented in a idtech4 engine is TheDarkMod's.

**Comment by ghost** [comment]
Did not know that, thanks. Will ask around on their forum about it and see how it is done on Dark Radiant.

**Comment by BielBdeLuna** [comment]
http://wiki.thedarkmod.com/index.php?title=LOD
http://wiki.thedarkmod.com/index.php?title=SEED

**Comment by ghost** [comment]
Thank you, this helps a lot. However will this be added into OTE as well? The alien planet level has outdoor areas which will be populated by various assets, I've sliced up some of the higher detailed terrain models to be lighter on the engine.

**Comment by BielBdeLuna** [comment]
not at the moment, but there is that implementation there.

what alien planet? are you making an alien planet?

**Comment by ghost** [comment]
I'm making a game to showcase the engine which will be released with the same license as the engine. I figured since there is so much to showcase then may as well make a mini fps game with various environments such as architectural, nature and of course the alien planet with funky effects.

**Comment by BielBdeLuna** [comment]
ok, it seems a fun project

**Comment by kortemik** [comment]
Would we be able to participate the development of it? It'd be much more
motivating to fix the issues and add features if we see any real progress
by them :)

**Comment by ghost** [comment]
@kortemik I would like that and would encourage it. First i want to finish the assets and maps before moving onto the code. The tech demo is more like a episodic based FPS like the shooters of the 90's.

I am releasing it free for the engine and would like to implement a donation system to help further development on the engine for purchasing hardware and software for contributors. This way we can test the engine on various hardware and optimize it. Another way donations can help is to improve on tutorials and produce media to help other developers get started on the engine.

I already have a site with a .com available which we can use for the game title and to host links to donations. I've already looked into using Patreon as well. There is however the concern of distributing the donations to everyone working on OTE so we can all benefit while improving on the engine.

Another idea I have for the game title is to create an asset store and have the public add onto the story and make money off it as well, this way we all benefit. Maybe the project can take a small cut of the sales to help invest in projects to fight issues such as poverty, hunger and help organisations provide education and free energy in areas which is in dire need.

**Comment by ghost** [comment]
Closing this. As for the alien planet, I've lost that file long ago, plus it is still hard to do vegetation. As a replacement, I have a large city file to replace it. Still need to unwrap and texture it.
