### ISSUE TITLE
PNG not showing up in DarkRadiant.

### ISSUE THREAD

**Issue by ghost** [OpenTechEngine/Discussions#27]
Seems the old issue has come back. The PNG files do not show in DarkRadiant and reverts to the shader not found image. For now I've reverted to using TGA's.

**Comment by kortemik** [comment]
How do you have your materials defined?

**Comment by ghost** [comment]
Yes I have. The PNG files for the lights also doesn't work, had to convert to TGA. It's DarkRadiant 2.0.3 with the last public build of OpenTech. 

EDIT FIXED//I can't setup the code to compile the engine, there is a cmakelists error "Expected a command name, got unquoted argument with text "<<<<<<<". was hoping there might be an error with the older build.//

**Comment by kortemik** [comment]
I will have to take a look at that somepoint, older release might work, i
think i used <2 version successfully..

**Comment by ghost** [comment]
@kortemik Just did a successful build of the engine, the PNG's work again. Not sure what happened with the older build.
