### ISSUE TITLE
OTE build issues.

### ISSUE THREAD

**Issue by ghost** [OpenTechEngine/Discussions#34]
I'm having issues building OTE on Windows 10, I've tried VS 2015, Eclipse and Codeblocks. All errors are different each attempt. I can't run the debug binaries provided by Kortemik on his sourceforge page, as I do not have VS 2013's debug libraries. Could one of you maybe provide me with a 64-bit release binary?

**Comment by kortemik** [comment]
Hello Yetta1

https://sourceforge.net/projects/opentechengine/files/snapshot/Windows/MinGW/

These should work without debug libraries.

**Comment by ghost** [comment]
@kortemik I'm currently using them, however I can't get PNG's to work on it. The PNG's are set up correctly for DarkRadiant, but in the engine itself it only renders the void. I can't seem to build the code on Windows, I've tried VS 2015, CodeBlocks, Cygwin and Mingw, all of them failed. I however did get it to build on Linux, but only a linux binary.

**Comment by ghost** [comment]
It's ok, I ended up downloading VS 2013 to build it. It worked.
