### ISSUE TITLE
Cegui GLSL sandbox

### ISSUE THREAD

**Issue by ghost** [OpenTechEngine/Discussions#4]
Would it be possible to integrate something like this into the cegui interface for shader experimentation real-time?

http://glslsandbox.com/e#26785.0

**Comment by kortemik** [comment]
You mean glsl or CG live editor?

**Comment by ghost** [comment]
GLSL/CG live editor/interpreter for testing shaders realtime in the engine, possibly in a special map containing something like a cornell box. Getting code results realtime and having the console save out the shaders to the game folders as the vertex and fragment files used in bfg would help a lot, instead of coding in a IDE/notepad, then loading the shader up in the console.

However I accept that it could also put stress on the engine and make it unstable depending on the code as it is interpreted. But if it is possible, then it could be a nice feature for other developers to use.

I'm still at a beginner level when it comes to programming, but have managed to create a 3D environment working with SDL2, I plan on learning more about the BSP format for the engine, ASSIMP, dmapping etc.

If I can manage, i'd like to create a level editor for OTE which has layers and some presets for easier level creation, like day/night cycling skies, drag and drop functionality and possibly group editing over lan/internet. SDL2 contains all the code to make it possible. So maybe a GLSL interpreter would be better suited for the editor. Radiant frustrates me a bit at times, so i'm really aiming at creating a more modern editor to work with OTE which could possibly generate scripts for models, materials, sounds, lights, fx.

I'm also looking into other libraries such as midi I/O and synthesis, so a live CG/GLSL interpreter would be nice in combination with that to create audio visualisers similar to what Winamp has. Having direct connection to Midi, synthesis, recording in the editor could also help game designers audio engineers design audio for their games within the editor. Could possibly also have particle fx react to the sound similar to what PopcornFX has. This also means that DJ's could use the engine at festivals to make particles and models react to the audio.

**Comment by ghost** [comment]
Closing this as it makes more sense to use third party software.
